<?php

namespace MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomeRepository extends EntityRepository
{
}
