main_front:
    resource: "@MainBundle/Controller/FrontController.php"
    type:     annotation
    prefix:   /

back_entreprise:
    resource: "@MainBundle/Controller/EntrepriseController.php"
    type:     annotation
    prefix:   /admin/entreprise

back_categorie:
    resource: "@MainBundle/Controller/CategorieController.php"
    type:     annotation
    prefix:   /admin/categorie

back_home:
    resource: "@MainBundle/Controller/HomeController.php"
    type:     annotation
    prefix:   /admin/home

back_user:
    resource: "@MainBundle/Controller/ClientController.php"
    type:     annotation
    prefix:   /admin/users

back_produit:
    resource: "@MainBundle/Controller/ProduitController.php"
    type:     annotation
    prefix:   /admin/produit
    
back_evenement:
    resource: "@MainBundle/Controller/EvenementController.php"
    type:     annotation
    prefix:   /admin/evenement
    
main_back:
    resource: "@MainBundle/Controller/BackController.php"
    type:     annotation
    prefix:   /admin


