main_front:
    resource: "@MainBundle/Controller/FrontController.php"
    type:     annotation
    prefix:   /

back_user:
    resource: "@MainBundle/Controller/ClientController.php"
    type:     annotation
    prefix:   /admin/users

back_produit:
    resource: "@MainBundle/Controller/ProduitController.php"
    type:     annotation
    prefix:   /admin/produit
    
back_evenement:
    resource: "@MainBundle/Controller/EvenementController.php"
    type:     annotation
    prefix:   /admin/evenement
    
main_back:
    resource: "@MainBundle/Controller/BackController.php"
    type:     annotation
    prefix:   /admin


