front:
    resource: "@FrontOfficeBundle/Controller/"
    type:     annotation
    prefix:   /

back_office:
    resource: "@BackOfficeBundle/Controller/"
    type:     annotation
    prefix:   /admin