main_front:
    resource: "@MainBundle/Controller/FrontController.php"
    type:     annotation
    prefix:   /

main_back:
    resource: "@MainBundle/Controller/BackController.php"
    type:     annotation
    prefix:   /admin

